name: CI/CD → Surge

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v3

      - name: 📦 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: 🔧 Install dependencies
        run: npm ci

      - name: 🔨 Build
        run: npm run build

      - name: 🚀 Install Surge
        run: npm install --global surge

      - name: 📤 Deploy to Surge
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
          SURGE_DOMAIN: ${{ secrets.SURGE_DOMAIN }}
        run: |
          surge ./build $SURGE_DOMAIN --token $SURGE_TOKEN
